name: CI

on:
  tags:
    - '*'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 5
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
      - run: yarn playwright install --with-deps chromium
      - run: yarn dev &
      - run: yarn test
        env:
          CI: true
      - uses: actions/upload-artifact@v3
        with:
          name: playwright-failed-test-traces
          path: test-results/
      - run: yarn build && tar -czvf release.tar.gz dist/
      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/') # if the push included a tag
        with:
          files: release.tar.gz