name: CI

on:
  push:
    tags:
      - '*'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 5
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
#      - name: Lint TODO uncomment
#        run: yarn lint
#      - run: yarn playwright install --with-deps chromium
#      - run: yarn dev &
#      - run: yarn test
#        env:
#          CI: true
#      - uses: actions/upload-artifact@v3
#        with:
#          name: playwright-failed-test-traces
#          path: test-results/
      - run: yarn build && tar -czvf release.tar.gz dist/
      - name: Checksums
        run: |
          echo "## Release Checksums" > ReleaseNotes.md
          echo "\`$(openssl dgst -sha3-256 release.tar.gz)\`" >> ReleaseNotes.md
          echo "\`$(openssl dgst -sha256 release.tar.gz)\`" >> ReleaseNotes.md
      - name: Prerelease
        uses: softprops/action-gh-release@v1
#        if: ${{ github.ref == 'refs/heads/automate_release' }} # if the pushing to main
        with:
          body_path: ReleaseNotes.md
          files: release.tar.gz
          prerelease: true
          name: dev
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/') # if the push included a tag
        with:
          body_path: ReleaseNotes.md
          files: release.tar.gz